# Generated by Django 4.2.30 on 2026-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_updated_at_orderitem_product_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Esperando confirmación', 'Esperando confirmación'), ('Pagado', 'Pagado'), ('Despachado', 'Despachado'), ('Cancelado', 'Cancelado')], db_index=True, default='Esperando confirmación', max_length=50),
        ),
    ]
