# Generated by Django 4.2.30 on 2026-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Esperando aprobacion', 'Esperando aprobacion'), ('Pago recibido', 'Pago recibido'), ('Pago no recibido', 'Pago no recibido'), ('Despachado', 'Despachado'), ('Cancelado', 'Cancelado')], db_index=True, default='Esperando aprobacion', max_length=50),
        ),
    ]
