# Generated by Django 4.2.30 on 2026-09-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('raquetas', 'Raquetas'), ('pelotas', 'Pelotas'), ('zapatillas', 'Zapatillas'), ('accesorios', 'Accesorios')], db_index=True, max_length=50),
        ),
    ]
