# Generated by Django 4.2.30 on 2026-09-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycard',
            name='store',
            field=models.CharField(choices=[('tenis', 'Tenis'), ('futbol', 'Fútbol')], default='tenis', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('raquetas', 'Raquetas'), ('pelotas', 'Pelotas'), ('zapatillas', 'Zapatillas'), ('accesorios', 'Accesorios'), ('zapatos_futbol', 'Zapatos Fútbol'), ('balones_futbol', 'Balones Fútbol'), ('equipamiento', 'Equipamiento'), ('entrenamiento', 'Entrenamiento'), ('tabla_a', 'Tabla A')], db_index=True, max_length=50),
        ),
    ]
