# Generated by Django 4.2.30 on 2026-09-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_categorycard_store_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('tenis', 'Tenis'), ('futbol', 'Fútbol')], default='tenis', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_in', to='store.product')),
            ],
            options={
                'verbose_name': 'Producto Destacado',
                'verbose_name_plural': 'Productos Destacados',
                'ordering': ['store', 'order'],
            },
        ),
    ]
