# Generated by Django 4.2.30 on 2026-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_featuredproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycard',
            name='store',
            field=models.CharField(choices=[('tenis', 'Tenis'), ('futbol', 'Fútbol'), ('meo_corte', 'Meo Corte')], default='tenis', max_length=15),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='store',
            field=models.CharField(choices=[('tenis', 'Tenis'), ('futbol', 'Fútbol'), ('meo_corte', 'Meo Corte')], default='tenis', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('raquetas', 'Raquetas'), ('pelotas', 'Pelotas'), ('zapatillas', 'Zapatillas'), ('accesorios', 'Accesorios'), ('zapatos_futbol', 'Zapatos Fútbol'), ('balones_futbol', 'Balones Fútbol'), ('equipamiento', 'Equipamiento'), ('entrenamiento', 'Entrenamiento'), ('tabla_a', 'Tabla A'), ('tillas', 'Tillas'), ('ropa_superior', 'Ropa Superior'), ('ropa_inferior', 'Ropa Inferior'), ('gorros', 'Gorros'), ('relojes', 'Relojes')], db_index=True, max_length=50),
        ),
    ]
